### ISSUE TITLE
Error calling script from NodeRed: __init__() should return None

### ISSUE THREAD

**Issue by fmarzocca** [jasonacox/tinytuya#114]
I can't use this library in a script called by Node Red. Every time the script executes:

`c = tinytuya.Cloud()`

I get this error:

```
Traceback (most recent call last):
  File .node-red/assets/testTuya.py", line 39, in <module>
    initialize()
  File ".node-red/assets/testTuya.py", line 22, in initialize
    c = tinytuya.Cloud()  
TypeError: __init__() should return None, not 'dict'
```

**Comment by jasonacox** [comment]
Hi @fmarzocca - I suspect the init() for the class is returning a JSON formatted error because you have not provided your Cloud API "Key" and "Secret".  If no parameters are sent in the init call, TinyTuya will attempt to read it from a local (current working directory) tinytuya.json file that was generated during the Wizard setup, but I suspect NodeRed doesn't allow or have access to that.

You should be able to fix this by specifying the credentials on the call:

```python
# OPTIONAL: Turn on Debug Mode
tinytuya.set_debug(True)

# Setup Cloud Connection
c = tinytuya.Cloud(
        apiRegion="us", 
        apiKey="xxxxxxxxxxxxxxxxxxxx", 
        apiSecret="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", 
        apiDeviceID="xxxxxxxxxxxxxxxxxxID")

# Display list of devices
devices = c.getdevices()
print("Device List: %r" % devices)

```
