### ISSUE TITLE
Adding device

### ISSUE THREAD

**Issue by louis49** [jasonacox/tinytuya#121]
Hi, 
I don't succeeded to add a device to my account.

I have multiple problems.

`python -m tinytuya scan`  give me : 

```
TinyTuya (Tuya device scanner) [1.3.1]

Scanning on UDP ports 6666 and 6667 for devices (15 retries)...

Unknown v3.3 Device   Product ID = keyf9fsmuufeywsr  [Valid payload]:
    Address = 192.168.1.15,  Device ID = 43070440e868e7d2e4XX, Local Key = ,  Version = 3.3
    No Stats for 192.168.1.15: DEVICE KEY required to poll for status
```

then, with : 
`python -m tinytuya wizard ` give me : 

```
TinyTuya Setup Wizard [1.3.1]
    Enter API Key from tuya.com: dsnhem48bg8wtxgrXXXXX
    Enter API Secret from tuya.com: 234cbc617d0d450394dbba15317XXXXX
    Enter any Device ID currently registered in Tuya App (used to pull full list): 43070440e868e7d2e4XX

      Region List
        cn	China Data Center
        us	US - Western America Data Center
        us-e	US - Eastern America Data Center
        eu	Central Europe Data Center
        eu-w	Western Europe Data Center
        in	India Data Center

    Enter Your Region (Options: cn, us, us-e, eu, eu-w, or in): eu-w

>> Configuration Data Saved to tinytuya.json
{
    "apiKey": "dsnhem48bg8wtxgrXXXXX",
    "apiSecret": "234cbc617d0d450394dbba15317XXXXX",
    "apiRegion": "eu-w",
    "apiDeviceID": "43070440e868e7d2e4XX"
}

**Error from Tuya server: permission deny**
```

When I use the app "iOT Device Management" to add device to my account, I have a "Login failed - The specified username or password is incorrect. Planse try again" error : 
![IMG_9301](https://user-images.githubusercontent.com/357595/160551031-857b46dd-c7fd-4ea9-b9e7-5de3571d841a.PNG)

When I use "Link Tuya App Account", I have a "CAPP_BINDED_USERID" error : 
<img width="1000" alt="Capture d’écran 2022-03-29 à 08 43 53" src="https://user-images.githubusercontent.com/357595/160550874-289806c8-daf3-467c-ab63-166c110afd94.png">

Any help please ?

**Comment by jasonacox** [comment]
Hi @louis49, this is the most confusing part of the setup. **Make sure you follow the steps as exact as possible ( [see here](https://github.com/jasonacox/tinytuya#setup-wizard---getting-local-keys) )**  If you have, I have some recommendations to consider:

* Why are you using the _IoT Device Management_ app?   You should not need that.  Use the _Smart Life App_  per the instructions ([here](https://github.com/jasonacox/tinytuya#setup-wizard---getting-local-keys)).  You will use the  _Smart Life App_  to scan the QR in [this step.](https://user-images.githubusercontent.com/836718/155827671-44d5fce4-0119-4d0e-a224-ef3715fafc24.png) to link your devices to your IoT account.
* Many people have reported issues with region not matching where they live.  Tuya will deny if it thinks you are not in the region you select based on your IP address.  For your setup, try 'eu' instead of 'eu-w' to see if that helps.  You will need to add this in the IoT setup as well as in the `wizard`.
* Ensure you set up the "Service API"" correctly - Under "Service API" ensure these APIs are listed: IoT Core, Authorization and Smart Home Scene Linkage.

**Comment by louis49** [comment]
Thank you a lot, it's now working : I haven't added Smart Home Scene Linkage Service Api
