### ISSUE TITLE
No data after Wizard

### ISSUE THREAD

**Issue by spamoi33** [jasonacox/tinytuya#35]
Hello all,
I get this error after wizard. I'm on Debian 10 in VM. Can you help me please ?

root@debian:/home/franck# python3 -m tinytuya wizard TinyTuya Setup Wizard [1.2.1]

Existing settings:
    API Key=xxx
    Secret=xxx
    DeviceID=xxx
    Region=eu

Use existing credentials (Y/n): Y
Traceback (most recent call last):
File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
"main", mod_spec)
File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
exec(code, run_globals)
File "/usr/local/lib/python3.7/dist-packages/tinytuya/main.py", line 48, in 
tinytuya.wizard(color)
File "/usr/local/lib/python3.7/dist-packages/tinytuya/init.py", line 1789, in wizard
uid = response_dict['result']['uid']
KeyError: 'result'
root@debian:/home/franck#

**Comment by jasonacox** [comment]
Hi @spamoi33 - the error you are getting indicates that TuyaCloud is not providing a response.  This can be caused by an error in the **API Key**, **Secret**, **DeviceID**, or **Region**. 

Log in to your Tuya Developer account on iot.tuya.com and verify that you have these settings correct.  Instructions are [here](https://github.com/jasonacox/tinytuya#get-the-tuya-device-local_key).

If it checks out and you are still getting the error, you can attempt the TuyAPI way:

```
npm i @tuyapi/cli -g 
tuya-cli wizard
```

**Comment by spamoi33** [comment]
Hi @jasonacox , thank you for your help, I forget a step ... ("Verify under Cloud Development -> select your project -> API Setting that the following API groups have status "Open": Authorization management, Device Management and Device Control (see here)")

Thank you again for this usefull tool ;)

**Comment by jasonacox** [comment]
My pleasure!  I'm glad it is working.
