### ISSUE TITLE
Error 901 , very new to python. 

### ISSUE THREAD

**Issue by beans14** [jasonacox/tinytuya#41]
Ok so when I tried the test file for an RGB bulb it would only change the color right after i turned the light off and then on again.After that it would not work until i turned it off and then on again.I am using a rasberry pi 4.

**Comment by beans14** [comment]
well now its saying error 905 not 901.@jasoncox

**Comment by jasonacox** [comment]
Both 901 and 905 are network errors ([see here](https://github.com/jasonacox/tinytuya#tinytuya-error-codes)) indicate that tinytuya is not able to communicate with the Tuya device.  It could be caused by network issues from the Raspberry PI to the device or it could be caused by another app.  Most Tuya devices can only handle one connection at a time  so if you have SmartLife App, Home Assistant or another app connecting to the Tuya device, tinytuya will throw network errors.

If you do no think it is a network issue and no other apps are connecting to the device, I would look at the debug output:

```python
import tinytuya
import time
import random

tinytuya.set_debug(True)  # use tinytuya.set_debug(True,False) for non-ANSI color terminal

d = tinytuya.BulbDevice(DEVICEID, DEVICEIP, DEVICEKEY)
d.set_version(3.3)

# Show status of device
data = d.status()
print('\nCurrent Status of Bulb: %r' % data)

# Set to full brightness warm white
print('\nWarm White Test')
d.set_white()
time.sleep(1)

# Power Control Test
print('\nPower Control Test')
print('    Turn off lamp')
d.turn_off()
time.sleep(1)
print('    Turn on lamp')
d.turn_on()
time.sleep(1)

# Random Color Test
print('\nRandom Color Test')
for x in range(10):
    r = random.randint(0, 255)
    g = random.randint(0, 255)
    b = random.randint(0, 255)
    print('    RGB (%d,%d,%d)' % (r, g, b))
    d.set_colour(r, g, b)
    time.sleep(1)

d.turn_off()
```

**Comment by beans14** [comment]
yes i forgot to put here i had fixed it.For some reason when i connected my light to alexa it would add one to the ip.And I also unsubscribed from uneeded api's.
