### ISSUE TITLE
Network Error: Device Unreachable

### ISSUE THREAD

**Issue by wongcheehong** [jasonacox/tinytuya#62]
I get device unreachable error when I have two interface connected, eth0 and wlan0 with ip address of 192.168.1.108 and 192.168.1.10 respectively. Any reason causing this happening?

**Comment by jasonacox** [comment]
Hi Friend, that appears to be a network routing problem, not really an issue with your Tuya device or the TintyTuya library.  I suspect you get the same result running a `ping 192.168.1.x` command?  Can you describe what is connected to eth0 and wlan0 (is it a linux box?) and paste your code and the output from Tinytuya?

**Comment by wongcheehong** [comment]
![image](https://user-images.githubusercontent.com/11075969/130585359-ee427c2f-788a-4ae3-b408-81b6c1e66695.png)
My raspberry pi is connected to eth0 and wlan0 but my tuya device is on wlan0. I try to ping the tuya device and I get this error `From 192.168.1.108 icmp_seq=1 Destination Host Unreachable`. Can TinyTuya specify which interface to use?

**Comment by wongcheehong** [comment]
I can get reply if I specify to use interface wlan0 with the command `ping -I wlan0 192.168.1.4`. Can I specified which interface to use for Tinytuya?

**Comment by jasonacox** [comment]
TinyTuya doesn't have that ability.  There is a way to do this in python by adding bind() but it isn't portable between OS versions from what I see.  The real issue here is that your Raspberry Pi and/or network configuration isn't set up correctly.  Do you have eth0 and wlan0 connected to the same router?  It should know how to route to the 192.168.1.4 address by itself (without forcing interface).  

Is your setup like this?
## Setup 1
```
[ RPi ] (wlan0)  <----wifi---> [ WiFi Router ] <----ethernet----> (eth0) [ RPi ]
                                    |
                                    | wifi
                                    |
                          [ Tuya Device 192.168.1.4 ]
```
 or more like this?
## Setup 2
```
[ WiFi Router ]  <----wifi---> (wlan0) [ RPi ] (eth0) <----ethernet----> [ Another network ???? ]
        |
        | wifi
        |
[ Tuya Device 192.168.1.4 ]
```

For Option 1 - you might try forcing a metic value for wlan0. Normally, the ethernet connection has the lowest metric, so it will be used as the preference. You can change that in `/etc/dhcpcd.conf`:
```
# Custom metric for eth0.
interface eth0
metric 300

# Custom metric for wlan0.
interface wlan0
metric 200
```

For Option 2 - if you are wanting the RPi to route traffic between wlan0 and eth0, you have to set it up. If you want the ethernet (eth0) to be a separate network, you really should use a different subnet (e.g. 192.168.2.0/24).

**Comment by wongcheehong** [comment]
I am using Setup 2. I have changed the subnet to 192.168.2.0 now it is working properly. Thank you @jasonacox

**Comment by darckat038** [comment]
Hi, I don't know if it's ok to write here, but my problem is similar. So I have a 3 Phases Power Clamp from Tuya, but when I try to connect to it or even pinging, i get "network error: destination unreachable". I run the ping command from a pc using ethernet which is on the same network as the power clamp. I though this could be a network problem, but i have also a Smart Meter from Tuya too, which is connected to the same network of the power clamp, and if i try to ping that one from the same pc, i get a positive response. I would like to add, but I dont' know if it is important or no, that i have 2 different networks with same name: the first working on 2.4ghz, and the second one working on 5ghz. Thanks
