### ISSUE TITLE
Device BTH-6000 Not found in tinytuya scan

### ISSUE THREAD

**Issue by mojtabavi** [jasonacox/tinytuya#70]
Hi
I have Beca, BTH-6000 wifi Thermostat Device that successfully connected to Smart Life app and work properly But cannot be found in tinytuya scan,
what's the problem??
please help
tnx

**Comment by jasonacox** [comment]
Hi @mojtabavi ,

 All Tuya devices, like the thermostat, are design to connect to the cloud as their primary communication channel. That is how the SmartLife app works as well.  They also provide a API for local communication which the SmartLife app will use after it connects to the cloud.  However, most of the API implementations will only allow for ONE connection at a time.  If you are running the SmartLife app, nothing else (including TinyTuya) can connect. 

First, close your SmartLife app.  Then run TinyTuya to scan the network and tell it to wait longer by giving it a larger timeout:
```
python -m tinytuya scan 50
```

If it still doesn't show up, it could be that this device is not set to broadcast UDP 6666 or 6667 packets for autodiscovery.   I only see that on devices that are battery powered, as a way for them to conserve energy, but it is rare.  Power cycling the device to also cause it to begin broadcasting itself for a short while, during which TinyTuya should be able to detect it.

Were you able to successfully get the local key for the device using the Wizard Setup (`python -m tinytuya wizard`)?

I do see some discussion about this device and some problem.  There is even a project to replace the firmware (https://github.com/klausahrenberg/WThermostatBeca) which does make me wonder why they went that way instead of using the local Tuya API.

**Comment by mojtabavi** [comment]
thanks for your help
I realize that the problem is with my windows
try with ubuntu and find the device id successfully
but in setup i got permission deny error
also try api explorer and still i got permission deny
what should i do?
i'm realy confused

**Comment by mojtabavi** [comment]
I follow the steps again, anc create new cloud,
my problem solved 
tnx
